INSERT INTO public.recipes (
    id, name, description, image_url, cuisine, category, food_type, 
    ingredients, instructions, preparation_time, cooking_time, total_time, 
    difficulty, servings, rating, tips, nutrition
) VALUES 
(
    '11111111-1111-1111-1111-111111111103',
    'Crispy South Indian Masala Dosa',
    'Golden fermented rice and lentil crepe stuffed with aromatic spiced potato masala, served with coconut chutney and tangy sambar.',
    'https://images.unsplash.com/photo-1668236543090-82eba5ee5976?w=800&auto=format&fit=crop&q=80',
    'South Indian',
    'Breakfast',
    'VEGETARIAN',
    '[{"name":"Dosa Batter (Rice & Urad Dal)","quantity":"3 cups (fermented)","isOptional":false},{"name":"Potatoes (Aloo)","quantity":"4 medium (boiled & mashed)","isOptional":false},{"name":"Onions","quantity":"2 medium (thinly sliced)","isOptional":false},{"name":"Mustard Seeds & Curry Leaves","quantity":"1 tsp seeds, 10 leaves","isOptional":false},{"name":"Turmeric Powder & Green Chilies","quantity":"1/2 tsp turmeric, 3 chilies slit","isOptional":false},{"name":"Ghee / Cooking Oil","quantity":"3 tbsp","isOptional":false}]'::jsonb,
    '[{"step":1,"text":"Heat 1 tbsp oil in a pan. Sputter mustard seeds, chana dal, green chilies, and curry leaves."},{"step":2,"text":"Add sliced onions and sauté until translucent. Add turmeric and salt."},{"step":3,"text":"Add roughly mashed boiled potatoes and 1/4 cup water. Simmer on low heat for 3-4 minutes to create the filling."},{"step":4,"text":"Heat a flat cast iron tawa. Pour a ladle of fermented dosa batter in the center and spread outward in circular motions."},{"step":5,"text":"Drizzle ghee around the edges and cook on medium heat until the base turns golden and crisp."},{"step":6,"text":"Place potato masala in the center, fold over, and serve hot with coconut chutney and sambar."}]'::jsonb,
    '20 mins',
    '15 mins',
    '35 mins',
    'Medium',
    4,
    4.9,
    ARRAY['Ensure the tawa is medium-hot before spreading batter; sprinkle water and wipe with cloth to regulate temperature.', 'Mash potatoes coarsely, not into a paste, for authentic texture.'],
    '{"calories":320,"protein":"6g","carbs":"52g","fat":"10g"}'::jsonb
),
(
    '11111111-1111-1111-1111-111111111104',
    'Amritsari Stuffed Aloo Paratha',
    'Crispy whole wheat flatbread generously stuffed with spiced mashed potatoes, fresh green chilies, and coriander, served with white butter.',
    'https://images.unsplash.com/photo-1626074353765-517a681e40be?w=800&auto=format&fit=crop&q=80',
    'North Indian',
    'Breakfast',
    'VEGETARIAN',
    '[{"name":"Whole Wheat Flour (Atta)","quantity":"2 cups","isOptional":false},{"name":"Potatoes (Aloo)","quantity":"3 large (boiled, peeled & grated)","isOptional":false},{"name":"Green Chilies & Fresh Ginger","quantity":"2 chilies chopped, 1 tsp grated ginger","isOptional":false},{"name":"Ajwain (Carom Seeds)","quantity":"1/2 tsp","isOptional":false},{"name":"Amchur (Dry Mango Powder) & Garam Masala","quantity":"1 tsp each","isOptional":false},{"name":"Desi Ghee or White Butter","quantity":"3 tbsp","isOptional":false}]'::jsonb,
    '[{"step":1,"text":"Knead wheat flour with water and a pinch of salt into a soft, pliable dough. Rest covered for 15 minutes."},{"step":2,"text":"In a bowl, mix grated boiled potatoes, green chilies, ginger, ajwain, amchur, garam masala, and fresh coriander."},{"step":3,"text":"Roll a ball of dough into a 4-inch disc. Place a generous ball of spiced potato filling in the center and seal edges tightly."},{"step":4,"text":"Gently roll the stuffed ball into an even, 7-8 inch paratha with light pressure to prevent tearing."},{"step":5,"text":"Roast on a hot tawa with ghee until crisp and spotted with golden brown on both sides."},{"step":6,"text":"Serve piping hot topped with a dollop of butter, cold curd, and spicy mango pickle."}]'::jsonb,
    '15 mins',
    '15 mins',
    '30 mins',
    'Easy',
    3,
    4.8,
    ARRAY['Cool boiled potatoes completely before mashing to ensure the filling stays dry and doesn''t tear the dough.', 'Use generous ghee for authentic dhabha-style crispiness.'],
    '{"calories":340,"protein":"8g","carbs":"58g","fat":"9g"}'::jsonb
),
(
    '11111111-1111-1111-1111-111111111105',
    'Steamed Fluffy Idli with Vegetable Sambar',
    'Pillowy soft fermented rice cakes paired with a hearty, tangy lentil stew simmered with drumsticks, tomatoes, and South Indian spices.',
    'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=800&auto=format&fit=crop&q=80',
    'South Indian',
    'Breakfast',
    'VEGETARIAN',
    '[{"name":"Idli Batter (Fermented Rice & Urad Dal)","quantity":"3 cups","isOptional":false},{"name":"Toor Dal (Pigeon Peas)","quantity":"1 cup","isOptional":false},{"name":"Drumstick & Shallots (Sambar Onions)","quantity":"1 drumstick cut, 10 shallots","isOptional":false},{"name":"Ripe Tomatoes","quantity":"2 medium (diced)","isOptional":false},{"name":"Sambar Powder","quantity":"2 tbsp","isOptional":false},{"name":"Tamarind Paste","quantity":"1 tbsp dissolved in 1/2 cup warm water","isOptional":false}]'::jsonb,
    '[{"step":1,"text":"Grease idli plates with sesame oil. Pour fermented batter into the moulds and steam for 10-12 minutes until cooked."},{"step":2,"text":"Pressure cook toor dal with turmeric and 3 cups water until mushy (about 4 whistles). Whisk smooth."},{"step":3,"text":"Boil drumsticks, shallots, and diced tomatoes with tamarind water, sambar powder, and salt until vegetables are tender."},{"step":4,"text":"Add cooked toor dal to the vegetable pot and simmer for 5 minutes."},{"step":5,"text":"Temper mustard seeds, fenugreek seeds, curry leaves, and asafoetida in ghee and pour over sambar."},{"step":6,"text":"Unmould warm idlis using a wet spoon and serve swimming in aromatic hot sambar."}]'::jsonb,
    '15 mins',
    '20 mins',
    '35 mins',
    'Easy',
    4,
    4.8,
    ARRAY['Ferment the batter in a warm corner for 10-12 hours until it rises and becomes frothy for the softest idlis.', 'Use small shallots (sambar onions) for authentic South Indian flavor.'],
    '{"calories":250,"protein":"9g","carbs":"48g","fat":"2g"}'::jsonb
),
(
    '11111111-1111-1111-1111-111111111106',
    'Mexican Black Bean & Tomato Breakfast Tacos',
    'Warm corn tortillas filled with cumin-spiced black beans, charred corn, fresh pico de gallo, avocado slices, and lime crema.',
    'https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?w=800&auto=format&fit=crop&q=80',
    'Mexican',
    'Breakfast',
    'VEGETARIAN',
    '[{"name":"Corn Tortillas","quantity":"6 small","isOptional":false},{"name":"Black Beans","quantity":"1 can (400g, rinsed and drained)","isOptional":false},{"name":"Ripe Tomatoes (Pico de Gallo)","quantity":"2 medium (finely diced)","isOptional":false},{"name":"Red Onion & Jalapeño","quantity":"1/2 onion diced, 1 jalapeño seeded","isOptional":false},{"name":"Fresh Cilantro & Lime","quantity":"1/4 cup chopped, 1 lime juiced","isOptional":false},{"name":"Ripe Avocado & Queso Fresco / Cheese","quantity":"1 avocado sliced, 1/2 cup crumbled cheese","isOptional":true}]'::jsonb,
    '[{"step":1,"text":"Toss diced tomatoes, red onion, jalapeño, cilantro, lime juice, and salt in a bowl to make fresh pico de gallo."},{"step":2,"text":"Warm 1 tbsp olive oil in a skillet. Add minced garlic, cumin, chili powder, and black beans with 2 tbsp water."},{"step":3,"text":"Coarsely mash half the black beans with the back of a fork and simmer for 4 minutes until warm and saucy."},{"step":4,"text":"Toast corn tortillas over an open flame or dry skillet for 30 seconds per side until warm and pliable."},{"step":5,"text":"Layer warm black beans into tortillas, top with fresh pico de gallo, avocado slices, and cheese."},{"step":6,"text":"Squeeze fresh lime wedges over top and serve immediately."}]'::jsonb,
    '10 mins',
    '10 mins',
    '20 mins',
    'Easy',
    2,
    4.7,
    ARRAY['Charring the corn tortillas on an open gas burner imparts authentic smokiness.', 'Drain and rinse black beans well to reduce excess sodium.'],
    '{"calories":310,"protein":"11g","carbs":"46g","fat":"9g"}'::jsonb
),
(
    '11111111-1111-1111-1111-111111111107',
    'Dhaba Style Dal Tadka with Steamed Basmati Rice',
    'Silky yellow lentils tempered twice with fragrant garlic, cumin seeds, tomatoes, and ghee-infused Kashmiri chilies.',
    'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=800&auto=format&fit=crop&q=80',
    'North Indian',
    'Lunch',
    'VEGETARIAN',
    '[{"name":"Toor Dal & Moong Dal","quantity":"3/4 cup toor dal, 1/4 cup yellow moong dal","isOptional":false},{"name":"Basmati Rice","quantity":"1.5 cups","isOptional":false},{"name":"Ripe Tomatoes","quantity":"2 medium (finely chopped)","isOptional":false},{"name":"Garlic Cloves","quantity":"6-8 cloves (finely minced)","isOptional":false},{"name":"Desi Ghee","quantity":"3 tbsp","isOptional":false},{"name":"Cumin seeds & Whole Red Chilies","quantity":"1.5 tsp cumin, 2 dry red chilies","isOptional":false},{"name":"Kasuri Methi & Fresh Coriander","quantity":"1 tsp kasuri methi, 2 tbsp coriander","isOptional":true}]'::jsonb,
    '[{"step":1,"text":"Pressure cook washed dals with turmeric, salt, and 3.5 cups water for 4 whistles until completely tender."},{"step":2,"text":"Cook soaked basmati rice with 3 cups water until fluffy; set aside."},{"step":3,"text":"In a pan, heat 2 tbsp ghee. Sauté cumin seeds, chopped onions, and tomatoes until soft and pulpy."},{"step":4,"text":"Pour cooked dal into the tomato gravy and adjust consistency with 1/2 cup hot water. Simmer 5 minutes."},{"step":5,"text":"Prepare the second tadka: heat 1 tbsp ghee in a small ladle, fry minced garlic, dried red chilies, and Kashmiri chili powder for 30 seconds."},{"step":6,"text":"Pour the sizzling garlic tadka directly over the dal. Garnish with crushed kasuri methi and serve hot with rice."}]'::jsonb,
    '10 mins',
    '20 mins',
    '30 mins',
    'Easy',
    3,
    4.8,
    ARRAY['Using a blend of toor dal and moong dal provides both richness and silky body.', 'Do not burn garlic in the final tadka; remove from heat as soon as it turns light golden.'],
    '{"calories":380,"protein":"14g","carbs":"64g","fat":"8g"}'::jsonb
),
(
    '11111111-1111-1111-1111-111111111108',
    'Chettinad Spicy Pepper Chicken Curry',
    'An explosive Tamil culinary classic featuring bone-in chicken simmered in freshly ground roasted peppercorns, fennel seeds, and curry leaves.',
    'https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?w=800&auto=format&fit=crop&q=80',
    'South Indian',
    'Lunch',
    'NON-VEGETARIAN',
    '[{"name":"Chicken (Bone-in cuts)","quantity":"500g","isOptional":false},{"name":"Black Peppercorns","quantity":"2 tbsp (freshly crushed)","isOptional":false},{"name":"Shallots / Sambar Onions","quantity":"15 pieces (sliced)","isOptional":false},{"name":"Ripe Tomatoes","quantity":"2 medium (chopped)","isOptional":false},{"name":"Fennel Seeds & Cumin Seeds","quantity":"1 tsp each","isOptional":false},{"name":"Ginger-Garlic Paste","quantity":"1.5 tbsp","isOptional":false},{"name":"Curry Leaves & Coconut Oil","quantity":"2 sprigs curry leaves, 2.5 tbsp oil","isOptional":false}]'::jsonb,
    '[{"step":1,"text":"Dry roast black peppercorns, fennel seeds, cumin seeds, and coriander seeds until fragrant; grind into a coarse spice mix."},{"step":2,"text":"Heat coconut oil in a clay pot or heavy pan. Sputter mustard seeds and a generous handful of curry leaves."},{"step":3,"text":"Add sliced shallots and sauté until golden brown. Add ginger-garlic paste and sauté for 1 minute."},{"step":4,"text":"Add chopped tomatoes and turmeric; cook until tomatoes break down into a rich paste."},{"step":5,"text":"Add chicken pieces and half the freshly ground pepper spice powder. Sear for 5 minutes on high heat."},{"step":6,"text":"Add 1 cup water, cover, and simmer for 18-20 minutes until chicken is tender. Stir in remaining black pepper powder before serving."}]'::jsonb,
    '15 mins',
    '25 mins',
    '40 mins',
    'Medium',
    3,
    4.9,
    ARRAY['Grind whole black peppercorns fresh; pre-ground pepper lacks the signature floral heat of Chettinad cuisine.', 'Coconut oil is essential for authentic South Indian aroma.'],
    '{"calories":430,"protein":"36g","carbs":"12g","fat":"26g"}'::jsonb
),
(
    '11111111-1111-1111-1111-111111111109',
    'Classic Italian Margherita Pizza',
    'Crisp artisanal crust topped with crushed San Marzano tomato sauce, creamy fresh mozzarella, fragrant sweet basil, and extra virgin olive oil.',
    'https://images.unsplash.com/photo-1604382355076-af4b0eb60143?w=800&auto=format&fit=crop&q=80',
    'Italian',
    'Lunch',
    'VEGETARIAN',
    '[{"name":"Pizza Dough (00 Flour / Yeast)","quantity":"1 ball (250g)","isOptional":false},{"name":"San Marzano Canned or Ripe Tomatoes","quantity":"1/2 cup (crushed with sea salt)","isOptional":false},{"name":"Fresh Mozzarella (Fior di Latte)","quantity":"150g (torn into chunks)","isOptional":false},{"name":"Fresh Sweet Basil Leaves","quantity":"8-10 whole leaves","isOptional":false},{"name":"Extra Virgin Olive Oil","quantity":"2 tbsp","isOptional":false},{"name":"Parmesan / Grana Padano Cheese","quantity":"1 tbsp finely grated","isOptional":true}]'::jsonb,
    '[{"step":1,"text":"Preheat oven with pizza stone or heavy baking tray at maximum heat (250°C / 485°F) for at least 30 minutes."},{"step":2,"text":"Stretch dough ball gently using your fingertips on a floured surface into a 10-12 inch round, leaving a raised outer crust."},{"step":3,"text":"Spread crushed tomato sauce thinly from the center outwards, leaving a 1-inch border."},{"step":4,"text":"Distribute torn fresh mozzarella chunks and a sprinkle of grated parmesan evenly over the sauce."},{"step":5,"text":"Slide onto the blazing hot pizza stone and bake for 8-10 minutes until cheese is bubbly and crust has charred leopard spots."},{"step":6,"text":"Scatter fresh basil leaves over top and finish with a swirl of extra virgin olive oil before slicing."}]'::jsonb,
    '20 mins',
    '10 mins',
    '30 mins',
    'Medium',
    2,
    4.9,
    ARRAY['Do not overload with tomato sauce; a thin layer ensures the crust remains crispy and not soggy.', 'Add fresh basil leaves after baking so their delicate herbal aroma stays vibrant.'],
    '{"calories":480,"protein":"19g","carbs":"62g","fat":"18g"}'::jsonb
),
(
    '11111111-1111-1111-1111-111111111110',
    'Szechuan Kung Pao Chicken',
    'A fiery stir-fried Chinese wok classic featuring tender diced chicken, crunchy roasted peanuts, dried red chilies, and scallions in savory sauce.',
    'https://images.unsplash.com/photo-1525755662778-989d0524087e?w=800&auto=format&fit=crop&q=80',
    'Chinese',
    'Lunch',
    'NON-VEGETARIAN',
    '[{"name":"Chicken Breast or Thighs","quantity":"400g (cut into 1-inch cubes)","isOptional":false},{"name":"Roasted Peanuts","quantity":"1/3 cup (unsalted)","isOptional":false},{"name":"Dried Red Szechuan Chilies","quantity":"8-10 pieces (halved, seeds shaken out)","isOptional":false},{"name":"Szechuan Peppercorns","quantity":"1 tsp","isOptional":false},{"name":"Spring Onions (Scallions)","quantity":"4 stalks (cut into 1-inch batons)","isOptional":false},{"name":"Soy Sauce & Chinkiang Black Vinegar","quantity":"2 tbsp soy sauce, 1.5 tbsp vinegar","isOptional":false},{"name":"Cornstarch & Shaoxing Wine / Broth","quantity":"1 tbsp cornstarch, 2 tbsp broth","isOptional":false}]'::jsonb,
    '[{"step":1,"text":"Marinate chicken cubes with 1 tbsp soy sauce, 1 tsp cornstarch, and pinch of salt for 15 minutes."},{"step":2,"text":"Whisk sauce: 1 tbsp soy sauce, black vinegar, 1 tsp sugar, 1 tsp cornstarch, and 2 tbsp water in a small bowl."},{"step":3,"text":"Heat 2 tbsp oil in a smoking-hot wok. Add dried chilies and Szechuan peppercorns; stir-fry for 15 seconds until aromatic."},{"step":4,"text":"Add marinated chicken and stir-fry vigorously for 3-4 minutes until chicken changes color and edges are seared."},{"step":5,"text":"Toss in minced garlic, ginger, and spring onions; stir-fry for 1 minute."},{"step":6,"text":"Pour in the sauce mixture and stir constantly until glossy. Fold in roasted peanuts and serve hot with rice."}]'::jsonb,
    '15 mins',
    '10 mins',
    '25 mins',
    'Medium',
    3,
    4.8,
    ARRAY['Keep your wok intensely hot and work fast to capture authentic wok hei (breath of the wok).', 'Add roasted peanuts at the very end to preserve their crisp texture.'],
    '{"calories":420,"protein":"34g","carbs":"14g","fat":"25g"}'::jsonb
),
(
    '11111111-1111-1111-1111-111111111111',
    'Authentic Punjabi Palak Paneer',
    'Tender cottage cheese cubes simmered in a velvety, emerald-green spiced spinach gravy enriched with cumin, garlic, and fresh cream.',
    'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=800&auto=format&fit=crop&q=80',
    'North Indian',
    'Dinner',
    'VEGETARIAN',
    '[{"name":"Fresh Spinach (Palak)","quantity":"400g (washed and trimmed)","isOptional":false},{"name":"Paneer (Cottage Cheese)","quantity":"250g (cubed)","isOptional":false},{"name":"Onions & Ripe Tomatoes","quantity":"1 large onion chopped, 2 tomatoes pureed","isOptional":false},{"name":"Garlic & Ginger","quantity":"1.5 tbsp minced garlic, 1 tbsp ginger","isOptional":false},{"name":"Desi Ghee or Butter","quantity":"2 tbsp","isOptional":false},{"name":"Garam Masala & Cumin","quantity":"1/2 tsp garam masala, 1 tsp cumin","isOptional":false},{"name":"Fresh Cream","quantity":"2 tbsp","isOptional":true}]'::jsonb,
    '[{"step":1,"text":"Blanch spinach leaves in boiling salted water for 2 minutes, then immediately plunge into an ice-water bath."},{"step":2,"text":"Drain spinach and blend with 1 green chili into a vibrant smooth green puree without adding excess water."},{"step":3,"text":"Heat ghee in a pan. Sputter cumin seeds and sauté minced garlic and onions until soft and light golden."},{"step":4,"text":"Add pureed tomatoes, turmeric, coriander powder, and salt. Cook 5 minutes until oil separates."},{"step":5,"text":"Pour in the vibrant spinach puree and simmer gently covered for 4-5 minutes."},{"step":6,"text":"Add paneer cubes, garam masala, and fresh cream. Cook for 2 minutes and serve warm with garlic naan."}]'::jsonb,
    '15 mins',
    '15 mins',
    '30 mins',
    'Easy',
    3,
    4.9,
    ARRAY['The ice-water bath immediately shocks the spinach and preserves the vibrant green restaurant color.', 'Do not overcook the spinach puree once added to keep nutrients and color fresh.'],
    '{"calories":340,"protein":"18g","carbs":"14g","fat":"24g"}'::jsonb
),
(
    '11111111-1111-1111-1111-111111111112',
    'Italian Spaghetti Bolognese',
    'Slow-simmered rich Italian meat sauce made with minced chicken, Italian plum tomatoes, aromatic mirepoix, and herbs tossed with al dente spaghetti.',
    'https://images.unsplash.com/photo-1551183053-bf91a1d81141?w=800&auto=format&fit=crop&q=80',
    'Italian',
    'Dinner',
    'NON-VEGETARIAN',
    '[{"name":"Spaghetti Pasta","quantity":"350g","isOptional":false},{"name":"Minced Chicken / Poultry Meat","quantity":"400g","isOptional":false},{"name":"Italian Whole Plum Tomatoes","quantity":"1 can (400g crushed)","isOptional":false},{"name":"Onion, Carrot & Celery (Mirepoix)","quantity":"1 onion, 1 carrot, 1 celery stick (finely minced)","isOptional":false},{"name":"Garlic & Olive Oil","quantity":"4 cloves minced, 2 tbsp olive oil","isOptional":false},{"name":"Dried Oregano & Fresh Basil","quantity":"1 tsp oregano, 5 leaves fresh basil","isOptional":false},{"name":"Grated Parmesan Cheese","quantity":"1/3 cup","isOptional":true}]'::jsonb,
    '[{"step":1,"text":"Heat olive oil in a heavy pot. Sauté finely minced onion, carrot, and celery over medium heat for 6-8 minutes until sweet and tender."},{"step":2,"text":"Add minced garlic and ground poultry meat. Cook breaking up clumps with a spoon until lightly browned (5-6 minutes)."},{"step":3,"text":"Pour in crushed plum tomatoes, tomato paste, dried oregano, salt, and black pepper. Stir well."},{"step":4,"text":"Cover and simmer sauce on low heat for 25-30 minutes, stirring occasionally until thick and rich."},{"step":5,"text":"Boil spaghetti in generously salted water until al dente (about 8-9 minutes); reserve 1/2 cup starchy pasta water."},{"step":6,"text":"Toss drained pasta directly into the Bolognese sauce with a splash of pasta water. Serve topped with parmesan and fresh basil."}]'::jsonb,
    '15 mins',
    '35 mins',
    '50 mins',
    'Medium',
    4,
    4.8,
    ARRAY['Finely mincing the vegetables (soffritto) allows them to melt into the meat sauce seamlessly.', 'Always finish the pasta in the sauce for 1 minute so the noodles absorb the savory juices.'],
    '{"calories":520,"protein":"32g","carbs":"65g","fat":"14g"}'::jsonb
),
(
    '11111111-1111-1111-1111-111111111113',
    'Sizzling Mexican Chicken Fajitas',
    'Juicy spiced chicken breast strips seared with sweet bell peppers and red onions, served with warm tortillas, guacamole, and lime.',
    'https://images.unsplash.com/photo-1534766555764-ce878a5e3a2b?w=800&auto=format&fit=crop&q=80',
    'Mexican',
    'Dinner',
    'NON-VEGETARIAN',
    '[{"name":"Chicken Breasts","quantity":"500g (cut into 1/2-inch strips)","isOptional":false},{"name":"Tri-color Bell Peppers (Capsicum)","quantity":"2 medium (sliced into strips)","isOptional":false},{"name":"Red Onion","quantity":"1 large (sliced into strips)","isOptional":false},{"name":"Fajita Seasoning (Cumin, Smoked Paprika, Garlic Powder)","quantity":"1.5 tbsp","isOptional":false},{"name":"Lime Juice & Olive Oil","quantity":"Juice of 1 lime, 2.5 tbsp oil","isOptional":false},{"name":"Warm Flour Tortillas","quantity":"6 tortillas","isOptional":true}]'::jsonb,
    '[{"step":1,"text":"Toss sliced chicken with fajita seasoning, lime juice, 1 tbsp olive oil, and salt. Marinate for 15 minutes."},{"step":2,"text":"Heat a cast-iron skillet over high heat with 1 tbsp oil until lightly smoking."},{"step":3,"text":"Add chicken strips in a single layer and sear for 3 minutes per side until nicely charred and cooked through; transfer to a plate."},{"step":4,"text":"Add remaining oil, bell peppers, and red onions to the hot skillet. Sauté vigorously for 4-5 minutes until tender-crisp with charred edges."},{"step":5,"text":"Return chicken and resting juices back to the sizzling skillet; toss together for 1 minute."},{"step":6,"text":"Serve sizzling straight from the pan with warm flour tortillas, fresh salsa, and cooling sour cream."}]'::jsonb,
    '15 mins',
    '15 mins',
    '30 mins',
    'Easy',
    3,
    4.8,
    ARRAY['A ripping hot cast iron skillet gives the classic restaurant sizzle and charred smoky flavor.', 'Keep peppers tender-crisp; overcooking makes them limp.'],
    '{"calories":440,"protein":"38g","carbs":"28g","fat":"20g"}'::jsonb
),
(
    '11111111-1111-1111-1111-111111111114',
    'Malabar Coconut Fish Curry',
    'Fresh kingfish steaks simmered in a velvety coconut milk gravy flavored with kudampuli (pot tamarind), mustard seeds, and fresh curry leaves.',
    'https://images.unsplash.com/photo-1620894580123-466ad3a0ca06?w=800&auto=format&fit=crop&q=80',
    'South Indian',
    'Dinner',
    'NON-VEGETARIAN',
    '[{"name":"Fish Steaks (Kingfish / Seer Fish)","quantity":"500g","isOptional":false},{"name":"Thick Coconut Milk & Thin Coconut Milk","quantity":"1 cup thick, 1 cup thin","isOptional":false},{"name":"Kudampuli (Malabar Tamarind)","quantity":"3 pieces (soaked in warm water)","isOptional":false},{"name":"Shallots & Green Chilies","quantity":"10 shallots sliced, 3 chilies slit","isOptional":false},{"name":"Ginger & Garlic Paste","quantity":"1 tbsp","isOptional":false},{"name":"Kashmiri Chili Powder & Turmeric","quantity":"1.5 tbsp chili, 1/2 tsp turmeric","isOptional":false},{"name":"Curry Leaves & Coconut Oil","quantity":"2 sprigs curry leaves, 2 tbsp oil","isOptional":false}]'::jsonb,
    '[{"step":1,"text":"Soak kudampuli pieces in 1/2 cup warm water for 15 minutes."},{"step":2,"text":"In an earthen manchatti (clay pot), heat coconut oil. Sputter mustard seeds, fenugreek seeds, and fresh curry leaves."},{"step":3,"text":"Add sliced shallots, ginger-garlic paste, and green chilies. Sauté until shallots turn soft."},{"step":4,"text":"Add Kashmiri chili powder, coriander powder, turmeric, thin coconut milk, soaked kudampuli water, and salt. Bring to a boil."},{"step":5,"text":"Gently slide in fish steaks. Cover and simmer gently on medium-low heat for 8-10 minutes."},{"step":6,"text":"Lower heat to lowest, pour in thick coconut milk, swirl pot gently without stirring with spoon, and turn off heat."}]'::jsonb,
    '15 mins',
    '20 mins',
    '35 mins',
    'Medium',
    3,
    4.9,
    ARRAY['Swirl the clay pot rather than stirring with a ladle to prevent delicate fish pieces from breaking.', 'Fish curry tastes even richer the next day as the coconut and tamarind penetrate the fish.'],
    '{"calories":390,"protein":"32g","carbs":"8g","fat":"26g"}'::jsonb
),
(
    '11111111-1111-1111-1111-111111111115',
    'Crispy Punjabi Potato & Pea Samosa',
    'Golden, triangular flaky pastries stuffed with a robustly spiced filling of cumin potatoes, green peas, pomegranate seeds, and ginger.',
    'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=800&auto=format&fit=crop&q=80',
    'North Indian',
    'Snacks',
    'VEGETARIAN',
    '[{"name":"All-Purpose Flour (Maida)","quantity":"2 cups","isOptional":false},{"name":"Potatoes (Aloo)","quantity":"4 medium (boiled & roughly crushed)","isOptional":false},{"name":"Green Peas (Matar)","quantity":"1/2 cup (boiled or fresh)","isOptional":false},{"name":"Ajwain (Carom Seeds)","quantity":"1 tsp","isOptional":false},{"name":"Coriander Seeds & Cumin Seeds","quantity":"1 tbsp coarsely crushed","isOptional":false},{"name":"Amchur (Dry Mango Powder) & Garam Masala","quantity":"1 tsp each","isOptional":false},{"name":"Cooking Oil or Ghee for Frying","quantity":"3 cups for deep frying, 4 tbsp for dough","isOptional":false}]'::jsonb,
    '[{"step":1,"text":"Rub 4 tbsp warm ghee into flour with ajwain and salt until it resembles breadcrumbs. Knead into a firm, stiff dough with cold water. Rest 20 mins."},{"step":2,"text":"Heat 1 tbsp oil in a pan. Fry crushed coriander seeds, cumin, ginger, and green chilies."},{"step":3,"text":"Add crushed potatoes, green peas, amchur, garam masala, and salt. Sauté for 4 minutes; cool completely."},{"step":4,"text":"Divide dough into balls, roll into oval discs, cut in half. Form a cone, fill with 2 tbsp potato mixture, and seal wet edges tightly."},{"step":5,"text":"Deep fry samosas in medium-low hot oil for 15-18 minutes until golden brown and super flaky."},{"step":6,"text":"Drain on paper towels and serve hot with sweet tamarind and spicy mint chutneys."}]'::jsonb,
    '25 mins',
    '20 mins',
    '45 mins',
    'Hard',
    4,
    4.9,
    ARRAY['The dough must be firm and stiff, not soft, to achieve the classic non-oily blister-free flaky crust.', 'Always fry on low-medium oil heat; high heat causes blisters and leaves the pastry doughy inside.'],
    '{"calories":310,"protein":"5g","carbs":"42g","fat":"14g"}'::jsonb
),
(
    '11111111-1111-1111-1111-111111111116',
    'Crispy Asian Vegetable Spring Rolls',
    'Golden crispy pastry rolls packed with wok-tossed julienned carrots, shredded cabbage, bell peppers, garlic, and sesame soy glaze.',
    'https://images.unsplash.com/photo-1541832676-9b763b0239ab?w=800&auto=format&fit=crop&q=80',
    'Chinese',
    'Snacks',
    'VEGETARIAN',
    '[{"name":"Spring Roll Wrappers / Sheets","quantity":"10 sheets","isOptional":false},{"name":"Carrots","quantity":"2 medium (finely julienned)","isOptional":false},{"name":"Green Cabbage","quantity":"2 cups (finely shredded)","isOptional":false},{"name":"Bell Pepper (Capsicum) & Spring Onion","quantity":"1/2 pepper julienned, 3 spring onions chopped","isOptional":false},{"name":"Soy Sauce & Sesame Oil","quantity":"1.5 tbsp soy sauce, 1 tsp sesame oil","isOptional":false},{"name":"Cornstarch & Oil for Frying","quantity":"1 tbsp cornstarch for slurry, oil for frying","isOptional":false}]'::jsonb,
    '[{"step":1,"text":"Heat 1 tbsp oil in a wok. Add minced garlic and ginger; sauté 30 seconds."},{"step":2,"text":"Add julienned carrots, cabbage, and bell peppers. Stir-fry on high heat for 2 minutes until vegetables are slightly tender but still crisp."},{"step":3,"text":"Add soy sauce, black pepper, and sesame oil. Stir well, transfer to a colander, and cool completely to drain excess moisture."},{"step":4,"text":"Place a spring roll wrapper with a corner pointing toward you. Add 2 tbsp cooled filling across the lower third."},{"step":5,"text":"Roll tightly halfway, fold in sides like an envelope, and seal the top corner with cornstarch slurry."},{"step":6,"text":"Deep fry in medium-hot oil for 4-5 minutes until golden and shatteringly crisp. Serve with sweet chili dip."}]'::jsonb,
    '20 mins',
    '15 mins',
    '35 mins',
    'Medium',
    4,
    4.8,
    ARRAY['Thoroughly drain and cool the vegetable filling before wrapping to prevent the spring roll skin from getting soggy.', 'Roll snugly to avoid trapping air pockets that can burst in hot oil.'],
    '{"calories":240,"protein":"4g","carbs":"32g","fat":"11g"}'::jsonb
),
(
    '11111111-1111-1111-1111-111111111117',
    'Loaded Mexican Fiesta Nachos',
    'Warm crispy tortilla chips smothered in melted cheddar cheese, black beans, diced tomatoes, pickled jalapeños, and fresh guacamole.',
    'https://images.unsplash.com/photo-1513456852971-30c0b8199d4d?w=800&auto=format&fit=crop&q=80',
    'Mexican',
    'Snacks',
    'VEGETARIAN',
    '[{"name":"Crisp Corn Tortilla Chips","quantity":"250g bag","isOptional":false},{"name":"Cheddar & Monterey Jack Cheese","quantity":"2 cups (freshly shredded)","isOptional":false},{"name":"Black Beans or Pinto Beans","quantity":"1 cup (cooked & seasoned)","isOptional":false},{"name":"Ripe Tomatoes & Jalapeños","quantity":"2 tomatoes diced, 2 tbsp sliced pickled jalapeños","isOptional":false},{"name":"Red Onion & Fresh Cilantro","quantity":"1/4 cup red onion diced, 2 tbsp cilantro","isOptional":false},{"name":"Guacamole & Sour Cream","quantity":"1/2 cup each","isOptional":true}]'::jsonb,
    '[{"step":1,"text":"Preheat oven to 200°C (400°F). Line a large baking sheet with parchment paper."},{"step":2,"text":"Spread half the tortilla chips in an even layer. Scatter half the seasoned black beans and half the shredded cheese."},{"step":3,"text":"Add the remaining chips in a second layer and top with remaining beans and generous shredded cheese."},{"step":4,"text":"Bake for 7-9 minutes until cheese is completely melted, gooey, and bubbling at the edges."},{"step":5,"text":"Remove from oven and scatter fresh diced tomatoes, red onions, jalapeños, and chopped cilantro over the hot cheese."},{"step":6,"text":"Dollop with creamy guacamole and sour cream; serve immediately while crunchy and hot."}]'::jsonb,
    '10 mins',
    '10 mins',
    '20 mins',
    'Easy',
    4,
    4.8,
    ARRAY['Layering the chips and cheese in two tiers prevents bare chips at the bottom.', 'Use block cheese and grate it fresh for the smoothest, gooiest melt.'],
    '{"calories":460,"protein":"16g","carbs":"44g","fat":"25g"}'::jsonb
),
(
    '11111111-1111-1111-1111-111111111118',
    'Crispy South Indian Chicken 65',
    'Iconic Chennai style spicy deep-fried chicken bites marinated in fiery red chilies, yogurt, curry leaves, and tempered garlic.',
    'https://images.unsplash.com/photo-1610057099443-fde8c4d50f91?w=800&auto=format&fit=crop&q=80',
    'South Indian',
    'Snacks',
    'NON-VEGETARIAN',
    '[{"name":"Boneless Chicken","quantity":"450g (cut into bite-sized 1-inch cubes)","isOptional":false},{"name":"Yogurt (Thick Curd)","quantity":"3 tbsp","isOptional":false},{"name":"Ginger-Garlic Paste","quantity":"1.5 tbsp","isOptional":false},{"name":"Kashmiri Red Chili Powder & Black Pepper","quantity":"1.5 tbsp chili, 1 tsp pepper","isOptional":false},{"name":"Corn Flour & Rice Flour","quantity":"2.5 tbsp corn flour, 1.5 tbsp rice flour","isOptional":false},{"name":"Curry Leaves & Green Chilies","quantity":"2 sprigs curry leaves, 4 chilies slit","isOptional":false},{"name":"Lemon Juice & Oil for Frying","quantity":"1 tbsp lemon juice, oil for deep frying","isOptional":false}]'::jsonb,
    '[{"step":1,"text":"Marinate chicken cubes with yogurt, ginger-garlic paste, red chili powder, turmeric, black pepper, lemon juice, and salt for 30 minutes."},{"step":2,"text":"Just before frying, dust in corn flour and rice flour; mix well so each piece has a light, even batter coating."},{"step":3,"text":"Heat oil in a wok. Drop chicken pieces one by one into hot oil and fry for 5-6 minutes until deep red, crisp, and cooked through."},{"step":4,"text":"Remove fried chicken and drain on paper towels."},{"step":5,"text":"In a separate pan, heat 1 tbsp oil. Sauté slit green chilies and fresh curry leaves until fragrant and sizzling."},{"step":6,"text":"Toss the fried chicken pieces in the tempered curry leaves and chilies; serve hot with sliced onions and lemon wedges."}]'::jsonb,
    '20 mins',
    '15 mins',
    '35 mins',
    'Medium',
    3,
    4.9,
    ARRAY['Rice flour added to the cornstarch batter gives that signature street-style shatteringly crisp crunch.', 'Tossing with sizzling curry leaves at the end infuses authentic aroma.'],
    '{"calories":380,"protein":"32g","carbs":"12g","fat":"22g"}'::jsonb
),
(
    '11111111-1111-1111-1111-111111111119',
    'Royal Shahi Gulab Jamun in Rose Saffron Syrup',
    'Melt-in-the-mouth fried milk dumpling sweets soaked in warm cardamom, rose water, and saffron infused sugar syrup.',
    'https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?w=800&auto=format&fit=crop&q=80',
    'Indian',
    'Dessert',
    'VEGETARIAN',
    '[{"name":"Khoya / Mawa (Evaporated Milk Solids)","quantity":"200g (grated)","isOptional":false},{"name":"Paneer (Chenna)","quantity":"75g (freshly grated and smooth)","isOptional":false},{"name":"All-Purpose Flour (Maida)","quantity":"3 tbsp","isOptional":false},{"name":"Baking Soda","quantity":"1/4 tsp","isOptional":false},{"name":"Sugar","quantity":"1.5 cups","isOptional":false},{"name":"Green Cardamom Pods & Rose Water","quantity":"4 crushed pods, 1 tsp rose water","isOptional":false},{"name":"Saffron Strands & Ghee for Frying","quantity":"pinch saffron, ghee for frying","isOptional":true}]'::jsonb,
    '[{"step":1,"text":"Boil sugar and 1.5 cups water with crushed cardamom pods and saffron for 6-8 minutes until slightly sticky (half-string consistency); stir in rose water."},{"step":2,"text":"In a wide plate, combine grated khoya and smooth paneer. Knead with the heel of your palm for 5 minutes until completely smooth."},{"step":3,"text":"Add maida and baking soda; knead into a soft, crack-free dough. Do not over-knead."},{"step":4,"text":"Roll into small smooth balls without any surface cracks."},{"step":5,"text":"Heat ghee on low heat. Gently drop jamuns and fry on gentle low heat for 10-12 minutes, swirling ghee gently until uniformly deep golden brown."},{"step":6,"text":"Drain and transfer warm gulab jamuns directly into warm sugar syrup. Let them soak for at least 1 hour before serving."}]'::jsonb,
    '20 mins',
    '20 mins',
    '40 mins',
    'Medium',
    4,
    4.9,
    ARRAY['Fry strictly on low heat so the centers cook through without burning the exterior.', 'The balls must have zero cracks on the surface to keep them perfectly smooth.'],
    '{"calories":310,"protein":"6g","carbs":"46g","fat":"12g"}'::jsonb
),
(
    '11111111-1111-1111-1111-111111111120',
    'Classic Italian Tiramisu',
    'An elegant no-bake Italian dessert made with coffee-dipped savoiardi ladyfingers layered with velvety whipped mascarpone cream and dusted with cocoa.',
    'https://images.unsplash.com/photo-1587314168485-3236d6710814?w=800&auto=format&fit=crop&q=80',
    'Italian',
    'Dessert',
    'VEGETARIAN',
    '[{"name":"Ladyfingers (Savoiardi Biscuits)","quantity":"24 biscuits","isOptional":false},{"name":"Mascarpone Cheese","quantity":"350g (chilled)","isOptional":false},{"name":"Heavy Whipping Cream","quantity":"1 cup (chilled)","isOptional":false},{"name":"Freshly Brewed Strong Espresso Coffee","quantity":"1.5 cups (cooled)","isOptional":false},{"name":"Powdered Sugar & Vanilla Extract","quantity":"1/2 cup sugar, 1 tsp vanilla","isOptional":false},{"name":"Dutch-Processed Dark Cocoa Powder","quantity":"2 tbsp for dusting","isOptional":false}]'::jsonb,
    '[{"step":1,"text":"Brew strong espresso coffee and let it cool completely in a shallow wide dish."},{"step":2,"text":"In a large chilled bowl, whip heavy cream with powdered sugar and vanilla extract until medium stiff peaks form."},{"step":3,"text":"Gently fold the softened mascarpone cheese into the whipped cream until luscious, smooth, and velvety."},{"step":4,"text":"Quickly dip ladyfingers into cooled espresso (1 second per side) and arrange in an even single layer at the bottom of an 8x8 inch glass dish."},{"step":5,"text":"Spread half of the mascarpone cream over the biscuits. Repeat with a second layer of dipped ladyfingers and remaining cream."},{"step":6,"text":"Dust generously with dark cocoa powder through a fine sieve. Refrigerate for at least 6 hours (or overnight) before serving."}]'::jsonb,
    '25 mins',
    '0 mins',
    '25 mins',
    'Easy',
    6,
    4.9,
    ARRAY['Do not soak ladyfingers for more than 1 second per side or the dessert will become watery.', 'Chilling overnight allows the flavors to meld and the cream to set firmly for clean slices.'],
    '{"calories":380,"protein":"6g","carbs":"38g","fat":"24g"}'::jsonb
),
(
    '11111111-1111-1111-1111-111111111121',
    'Creamy Kesari Mango Kulfi',
    'Traditional dense Indian frozen dessert crafted from slow-simmered caramelized whole milk, sweet Alphonso mangoes, pistachios, and saffron.',
    'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=800&auto=format&fit=crop&q=80',
    'Indian',
    'Dessert',
    'VEGETARIAN',
    '[{"name":"Full Fat Whole Milk","quantity":"1 liter","isOptional":false},{"name":"Ripe Alphonso Mango Puree","quantity":"1 cup","isOptional":false},{"name":"Condensed Milk","quantity":"1/2 cup","isOptional":false},{"name":"Cardamom Powder","quantity":"1/2 tsp","isOptional":false},{"name":"Pistachios & Almonds","quantity":"2 tbsp (finely chopped)","isOptional":false},{"name":"Saffron Strands","quantity":"10-12 strands soaked in 1 tbsp milk","isOptional":true}]'::jsonb,
    '[{"step":1,"text":"Bring whole milk to a boil in a wide, heavy-bottomed pan."},{"step":2,"text":"Simmer on medium-low heat for 35-40 minutes, scraping milk solids from sides of pan, until milk reduces to one-third volume (rabri consistency)."},{"step":3,"text":"Stir in condensed milk, soaked saffron milk, and cardamom powder; simmer for another 2 minutes and turn off heat."},{"step":4,"text":"Cool the reduced milk mixture completely to room temperature."},{"step":5,"text":"Whisk in the fresh mango puree and chopped pistachios until smooth and homogeneous."},{"step":6,"text":"Pour into kulfi moulds or popsicles, insert sticks, and freeze for at least 8 hours until solid. Unmould by rubbing between palms."}]'::jsonb,
    '15 mins',
    '45 mins',
    '60 mins',
    'Medium',
    4,
    4.8,
    ARRAY['Never add mango puree to hot reduced milk or the milk may curdle; ensure the mixture is completely cool.', 'Slow reduction is key to achieving that signature dense, creamy kulfi texture without ice crystals.'],
    '{"calories":280,"protein":"8g","carbs":"36g","fat":"12g"}'::jsonb
),
(
    '11111111-1111-1111-1111-111111111122',
    'Lucknowi Vegetable Dum Biryani',
    'Fragrant Awadhi royal basmati rice layered with garden vegetables, paneer cubes, saffron milk, fried onions, and whole aromatic spices.',
    'https://images.unsplash.com/photo-1645177628172-a94c1f96e6db?w=800&auto=format&fit=crop&q=80',
    'Indian',
    'Rice',
    'VEGETARIAN',
    '[{"name":"Aged Basmati Rice","quantity":"2 cups (soaked 30 mins)","isOptional":false},{"name":"Carrots, Beans, Potatoes & Peas","quantity":"2 cups mixed (cut into 1-inch pieces)","isOptional":false},{"name":"Paneer (Cottage Cheese)","quantity":"150g (cubed and lightly browned)","isOptional":false},{"name":"Thick Yogurt / Curd","quantity":"1/2 cup","isOptional":false},{"name":"Fried Onions (Birista)","quantity":"1 cup","isOptional":false},{"name":"Biryani Masala & Shahi Jeera","quantity":"1.5 tsp each","isOptional":false},{"name":"Saffron Warm Milk & Ghee","quantity":"2 tbsp milk with saffron, 2 tbsp ghee","isOptional":true}]'::jsonb,
    '[{"step":1,"text":"Parboil soaked basmati rice with whole spices (bay leaf, cloves, cardamom) until 70% cooked (about 6 minutes); drain completely."},{"step":2,"text":"Marinate vegetables and paneer in yogurt, ginger-garlic paste, biryani masala, half the fried onions, and salt for 20 minutes."},{"step":3,"text":"In a heavy pot, cook marinated vegetable mixture for 6 minutes until vegetables are half-tender."},{"step":4,"text":"Layer the parboiled rice evenly over the vegetables in the pot."},{"step":5,"text":"Drizzle saffron milk, rose water, remaining fried onions, mint, and generous ghee over top."},{"step":6,"text":"Seal pot tightly with dough or foil and heavy lid. Cook on low heat (dum) over a tawa for 25 minutes. Rest 10 minutes before fluffing."}]'::jsonb,
    '25 mins',
    '35 mins',
    '60 mins',
    'Medium',
    4,
    4.8,
    ARRAY['Keep vegetables in generous pieces so they hold their shape during the dum cooking phase.', 'Cook on a flat tawa on low flame to ensure the bottom does not scorch.'],
    '{"calories":450,"protein":"12g","carbs":"72g","fat":"14g"}'::jsonb
),
(
    '11111111-1111-1111-1111-111111111123',
    'Yangchow Vegetable Fried Rice',
    'High-heat wok-tossed jasmine rice with tender carrots, green peas, sweet corn, scallions, and a touch of light soy sauce and toasted sesame oil.',
    'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=800&auto=format&fit=crop&q=80',
    'Chinese',
    'Rice',
    'VEGETARIAN',
    '[{"name":"Cooked Jasmine or Long Grain Rice (Chilled)","quantity":"3 cups (day-old rice)","isOptional":false},{"name":"Carrots","quantity":"1 medium (finely diced)","isOptional":false},{"name":"Green Peas & Sweet Corn","quantity":"1/3 cup peas, 1/3 cup corn","isOptional":false},{"name":"Spring Onions (Scallions)","quantity":"3 stalks (chopped whites and greens separated)","isOptional":false},{"name":"Garlic & Ginger","quantity":"1 tbsp minced","isOptional":false},{"name":"Light Soy Sauce & Toasted Sesame Oil","quantity":"1.5 tbsp soy sauce, 1 tsp sesame oil","isOptional":false}]'::jsonb,
    '[{"step":1,"text":"Break up chilled day-old rice clumps with your fingers so grains separate cleanly."},{"step":2,"text":"Heat 2 tbsp oil in a smoking-hot wok over high flame."},{"step":3,"text":"Add minced garlic, ginger, and spring onion whites; stir-fry for 20 seconds."},{"step":4,"text":"Add diced carrots, sweet corn, and green peas; toss rapidly for 2 minutes."},{"step":5,"text":"Add cold rice into the center. Stir-fry and toss continuously for 3 minutes over maximum heat."},{"step":6,"text":"Drizzle light soy sauce and white pepper around the edges of the wok; finish with spring onion greens and sesame oil."}]'::jsonb,
    '10 mins',
    '10 mins',
    '20 mins',
    'Easy',
    3,
    4.8,
    ARRAY['Always use cold, day-old refrigerated rice; freshly boiled warm rice becomes mushy and clumps.', 'Drizzle soy sauce along the scorching hot sides of the wok rather than directly on rice for a smoky caramelized flavor.'],
    '{"calories":340,"protein":"7g","carbs":"62g","fat":"8g"}'::jsonb
),
(
    '11111111-1111-1111-1111-111111111124',
    'Mexican Arroz Rojo (Spiced Tomato Rice)',
    'Golden long grain rice toasted in olive oil and simmered in a puree of ripe fresh tomatoes, onions, garlic, cumin, and vegetable broth.',
    'https://images.unsplash.com/photo-1596797038530-2c107229654b?w=800&auto=format&fit=crop&q=80',
    'Mexican',
    'Rice',
    'VEGETARIAN',
    '[{"name":"Long Grain White Rice","quantity":"1.5 cups (rinsed & drained dry)","isOptional":false},{"name":"Ripe Tomatoes","quantity":"3 medium (roughly chopped)","isOptional":false},{"name":"White Onion & Garlic","quantity":"1/2 onion, 3 garlic cloves","isOptional":false},{"name":"Vegetable Broth or Water","quantity":"2.5 cups","isOptional":false},{"name":"Ground Cumin & Oregano","quantity":"1 tsp cumin, 1/2 tsp oregano","isOptional":false},{"name":"Cooking Oil & Fresh Cilantro","quantity":"2.5 tbsp oil, 2 tbsp chopped cilantro","isOptional":false}]'::jsonb,
    '[{"step":1,"text":"Blend chopped tomatoes, onion, garlic, and 1/2 cup broth into a silky smooth tomato puree."},{"step":2,"text":"Heat oil in a medium saucepan over medium-high heat. Add dried rice grains and toast, stirring constantly, for 5-6 minutes until light golden and nutty."},{"step":3,"text":"Pour in tomato puree; cook stirring for 2-3 minutes until tomato paste is slightly reduced and absorbed by rice."},{"step":4,"text":"Pour in remaining 2 cups vegetable broth, cumin, oregano, and salt. Bring to a rolling boil."},{"step":5,"text":"Cover with a tight-fitting lid, lower heat to lowest setting, and simmer undisturbed for 18 minutes."},{"step":6,"text":"Remove from heat and let sit covered for 10 minutes. Fluff gently with a fork and garnish with chopped fresh cilantro."}]'::jsonb,
    '10 mins',
    '25 mins',
    '35 mins',
    'Easy',
    4,
    4.8,
    ARRAY['Toasting the raw rice in oil until golden is the secret to grains that never get sticky or mushy.', 'Do not open the lid while simmering to retain steam.'],
    '{"calories":290,"protein":"5g","carbs":"54g","fat":"7g"}'::jsonb
),
(
    '11111111-1111-1111-1111-111111111125',
    'Fiery Schezwan Chicken Fried Rice',
    'Spicy Indo-Chinese street-style wok rice loaded with shredded chicken, crunchy carrots, scallions, and fiery homemade Schezwan red pepper paste.',
    'https://images.unsplash.com/photo-1512058564366-18510be2db19?w=800&auto=format&fit=crop&q=80',
    'Chinese',
    'Rice',
    'NON-VEGETARIAN',
    '[{"name":"Cooked Cold Basmati or Jasmine Rice","quantity":"3 cups","isOptional":false},{"name":"Chicken Breast","quantity":"250g (shredded or diced small)","isOptional":false},{"name":"Schezwan Sauce","quantity":"2.5 tbsp","isOptional":false},{"name":"Carrots & French Beans","quantity":"1/2 cup each (finely chopped)","isOptional":false},{"name":"Spring Onions & Garlic","quantity":"3 stalks spring onions, 1 tbsp minced garlic","isOptional":false},{"name":"Soy Sauce & Vinegar","quantity":"1 tbsp soy sauce, 1 tsp vinegar","isOptional":false}]'::jsonb,
    '[{"step":1,"text":"Heat 2 tbsp oil in a wok. Sauté minced garlic and celery for 30 seconds on high flame."},{"step":2,"text":"Add chicken shreds and stir-fry vigorously for 3-4 minutes until cooked through and lightly browned."},{"step":3,"text":"Toss in finely chopped carrots and french beans; stir-fry for 2 minutes to keep them crisp."},{"step":4,"text":"Add Schezwan sauce, soy sauce, and vinegar; stir well to coat chicken and vegetables."},{"step":5,"text":"Add cold rice and toss on maximum heat for 3-4 minutes until rice grains turn fiery red and aromatic."},{"step":6,"text":"Garnish with freshly chopped spring onion greens and serve piping hot."}]'::jsonb,
    '15 mins',
    '12 mins',
    '27 mins',
    'Easy',
    3,
    4.8,
    ARRAY['Toss on highest possible heat so the rice gets smoky street-style aroma.', 'Use refrigerated leftover rice for separate, firm grains.'],
    '{"calories":480,"protein":"28g","carbs":"64g","fat":"12g"}'::jsonb
),
(
    '11111111-1111-1111-1111-111111111126',
    'Homestyle Aloo Gobi Matar Curry',
    'Classic North Indian comforting homestyle curry with tender potatoes, cauliflower florets, and sweet green peas in spiced tomato masala.',
    'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=800&auto=format&fit=crop&q=80',
    'North Indian',
    'Curry',
    'VEGETARIAN',
    '[{"name":"Potatoes (Aloo)","quantity":"2 medium (cut into chunks)","isOptional":false},{"name":"Cauliflower (Gobi)","quantity":"1 small head (cut into bite-sized florets)","isOptional":false},{"name":"Green Peas (Matar)","quantity":"1/2 cup (fresh or frozen)","isOptional":false},{"name":"Ripe Tomatoes","quantity":"2 large (finely pureed)","isOptional":false},{"name":"Onions & Ginger-Garlic Paste","quantity":"1 onion chopped, 1 tbsp paste","isOptional":false},{"name":"Turmeric, Coriander Powder & Garam Masala","quantity":"1 tsp each","isOptional":false}]'::jsonb,
    '[{"step":1,"text":"Heat 2 tbsp oil in a pan. Sauté cauliflower florets and potato cubes for 5 minutes until lightly browned; set aside."},{"step":2,"text":"In the same pan, sputter cumin seeds, add chopped onions, and sauté until golden."},{"step":3,"text":"Add ginger-garlic paste and sauté for 1 minute until fragrant."},{"step":4,"text":"Pour in pureed tomatoes, turmeric, red chili powder, coriander powder, and salt. Cook until oil separates."},{"step":5,"text":"Add browned potatoes, cauliflower, green peas, and 1 cup water. Cover and simmer on low heat for 12-14 minutes."},{"step":6,"text":"Sprinkle garam masala and chopped coriander leaves; serve hot with phulkas or parathas."}]'::jsonb,
    '15 mins',
    '20 mins',
    '35 mins',
    'Easy',
    3,
    4.8,
    ARRAY['Pan-frying cauliflower florets first keeps them firm and prevents them from getting mushy in the curry.', 'A dash of kasuri methi crushed at the end elevates the aroma.'],
    '{"calories":260,"protein":"7g","carbs":"44g","fat":"8g"}'::jsonb
),
(
    '11111111-1111-1111-1111-111111111127',
    'Restaurant Style Murgh Makhani (Butter Chicken)',
    'Tender marinated roasted chicken pieces simmered in an indulgent, velvety smooth tomato, butter, and cashew nut gravy.',
    'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=800&auto=format&fit=crop&q=80',
    'North Indian',
    'Curry',
    'NON-VEGETARIAN',
    '[{"name":"Chicken Thighs (Boneless cuts)","quantity":"500g","isOptional":false},{"name":"Ripe Tomatoes","quantity":"5 large (boiled and blended silky smooth)","isOptional":false},{"name":"Cashews (Kaju)","quantity":"15 pieces (soaked and ground to paste)","isOptional":false},{"name":"Butter (Makhan)","quantity":"3 tbsp","isOptional":false},{"name":"Heavy Fresh Cream","quantity":"3 tbsp","isOptional":false},{"name":"Kasuri Methi (Dried Fenugreek)","quantity":"1 tbsp (crushed)","isOptional":false},{"name":"Kashmiri Chili Powder & Garam Masala","quantity":"1.5 tbsp chili, 1 tsp garam masala","isOptional":false}]'::jsonb,
    '[{"step":1,"text":"Marinate chicken with yogurt, Kashmiri chili powder, ginger-garlic paste, and lemon juice for 1 hour."},{"step":2,"text":"Pan-sear or broil chicken pieces on high heat for 8 minutes until lightly charred and 80% cooked; set aside."},{"step":3,"text":"Melt 2 tbsp butter in a pot. Add strained silky tomato puree and Kashmiri chili powder; simmer for 10 minutes."},{"step":4,"text":"Add cashew paste, 1/2 tsp sugar, and salt. Cook on low heat for 5 minutes until glossy."},{"step":5,"text":"Slide in charred chicken pieces, remaining 1 tbsp butter, and heavy cream. Simmer gently for 5 minutes."},{"step":6,"text":"Rub kasuri methi between palms and sprinkle over top. Serve with butter garlic naan."}]'::jsonb,
    '20 mins',
    '25 mins',
    '45 mins',
    'Medium',
    4,
    4.9,
    ARRAY['Strain the tomato puree through a fine sieve for that signature velvety restaurant silkiness.', 'Use bone-in or thigh meat for the juiciest texture.'],
    '{"calories":540,"protein":"38g","carbs":"14g","fat":"38g"}'::jsonb
),
(
    '11111111-1111-1111-1111-111111111128',
    'Goan Coconut Prawn Balchão Curry',
    'Plump succulent tiger prawns cooked in a spicy, tangy Goan coconut curry with tamarind pulp, dried red chilies, and coconut vinegar.',
    'https://images.unsplash.com/photo-1565680018434-b513d5e5fd47?w=800&auto=format&fit=crop&q=80',
    'Indian',
    'Curry',
    'NON-VEGETARIAN',
    '[{"name":"Tiger Prawns / Shrimp","quantity":"400g (shelled and deveined)","isOptional":false},{"name":"Fresh Grated Coconut","quantity":"1 cup","isOptional":false},{"name":"Kashmiri Dried Red Chilies","quantity":"5 pieces (soaked in warm water)","isOptional":false},{"name":"Tamarind Pulp","quantity":"1.5 tbsp","isOptional":false},{"name":"Onion & Garlic","quantity":"1 onion finely chopped, 6 cloves garlic","isOptional":false},{"name":"Coconut Oil & Curry Leaves","quantity":"2 tbsp coconut oil, 1 sprig curry leaves","isOptional":false}]'::jsonb,
    '[{"step":1,"text":"Blend grated coconut, soaked red chilies, garlic, coriander seeds, cumin, and tamarind with 1/2 cup water into a fine spice paste."},{"step":2,"text":"Heat coconut oil in a pan. Sauté chopped onions and green chilies until translucent."},{"step":3,"text":"Pour in the ground Goan coconut masala paste and cook on medium heat for 4-5 minutes until oil glazes the sides."},{"step":4,"text":"Add 1 cup water and salt; bring curry to a gentle simmer."},{"step":5,"text":"Add cleaned prawns to the bubbling curry. Cook for just 3-4 minutes until prawns curl into a ''C'' shape and turn opaque pink."},{"step":6,"text":"Turn off heat immediately to prevent prawns from overcooking. Serve hot with steamed Goan red rice or basmati."}]'::jsonb,
    '15 mins',
    '15 mins',
    '30 mins',
    'Medium',
    3,
    4.8,
    ARRAY['Prawns cook in under 4 minutes; overcooking makes them rubbery.', 'Tamarind provides the quintessential Goan sour counter-balance to coconut milk.'],
    '{"calories":330,"protein":"28g","carbs":"9g","fat":"20g"}'::jsonb
),
(
    '11111111-1111-1111-1111-111111111129',
    'Roasted Fresh Tomato & Basil Soup',
    'Slow-roasted vine ripe tomatoes, caramelized garlic, and sweet onions blended with fresh Italian basil and a swirl of cream.',
    'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800&auto=format&fit=crop&q=80',
    'Italian',
    'Soup',
    'VEGETARIAN',
    '[{"name":"Ripe Vine Tomatoes","quantity":"1 kg (halved)","isOptional":false},{"name":"Garlic Head","quantity":"1 whole head (top sliced off)","isOptional":false},{"name":"Yellow Onion","quantity":"1 large (quartered)","isOptional":false},{"name":"Fresh Basil Leaves","quantity":"1 cup firmly packed","isOptional":false},{"name":"Vegetable Broth","quantity":"2 cups","isOptional":false},{"name":"Extra Virgin Olive Oil & Cream","quantity":"3 tbsp olive oil, 2 tbsp cream","isOptional":false}]'::jsonb,
    '[{"step":1,"text":"Preheat oven to 200°C (400°F). Arrange halved tomatoes, quartered onion, and garlic head on a baking tray."},{"step":2,"text":"Drizzle generously with olive oil, sea salt, and black pepper. Roast for 30 minutes until tomatoes are slightly charred and caramelized."},{"step":3,"text":"Squeeze roasted garlic cloves out of skins into a blender with the roasted tomatoes, onions, and pan juices."},{"step":4,"text":"Add fresh basil leaves and vegetable broth; blend on high speed until completely smooth and velvety."},{"step":5,"text":"Pour soup into a pot, warm through for 3 minutes, and adjust seasoning."},{"step":6,"text":"Ladle into warm bowls, swirl with cream, garnish with basil, and serve with crusty garlic bread."}]'::jsonb,
    '10 mins',
    '35 mins',
    '45 mins',
    'Easy',
    4,
    4.8,
    ARRAY['Roasting caramelizes the natural sugars in tomatoes, eliminating any harsh acidity without needing sugar.', 'Squeeze the roasted garlic right into the blender for deep, mellow sweetness.'],
    '{"calories":180,"protein":"4g","carbs":"20g","fat":"10g"}'::jsonb
),
(
    '11111111-1111-1111-1111-111111111130',
    'Szechuan Hot & Sour Chicken Soup',
    'A comforting, spicy and tangy Chinese soup with shredded chicken breast, wood ear mushrooms, bamboo shoots, tofu, and silky egg ribbons.',
    'https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?w=800&auto=format&fit=crop&q=80',
    'Chinese',
    'Soup',
    'NON-VEGETARIAN',
    '[{"name":"Chicken Breast","quantity":"200g (boiled and finely shredded)","isOptional":false},{"name":"Chicken Broth / Stock","quantity":"4 cups","isOptional":false},{"name":"Mushrooms (Wood Ear or Shiitake)","quantity":"1/2 cup (sliced)","isOptional":false},{"name":"Bamboo Shoots","quantity":"1/3 cup (julienned)","isOptional":false},{"name":"Chinkiang Black Vinegar or Rice Vinegar","quantity":"3 tbsp","isOptional":false},{"name":"Coarsely Ground White Pepper & Soy Sauce","quantity":"1.5 tsp white pepper, 2 tbsp soy sauce","isOptional":false},{"name":"Cornstarch & Sesame Oil","quantity":"2.5 tbsp cornstarch slurry, 1 tsp sesame oil","isOptional":false}]'::jsonb,
    '[{"step":1,"text":"Bring chicken broth to a gentle simmer in a soup pot."},{"step":2,"text":"Add shredded chicken, sliced mushrooms, and bamboo shoots; simmer for 5 minutes."},{"step":3,"text":"Stir in soy sauce, chili paste, white pepper, and salt."},{"step":4,"text":"Stir cornstarch with 3 tbsp cold water; pour into simmering soup while stirring until broth turns clear and glossy."},{"step":5,"text":"Turn off heat and immediately stir in black vinegar and toasted sesame oil."},{"step":6,"text":"Ladle into soup bowls, top with sliced green spring onions, and serve steaming hot."}]'::jsonb,
    '15 mins',
    '15 mins',
    '30 mins',
    'Medium',
    4,
    4.8,
    ARRAY['Add vinegar at the very end after turning off heat; boiling vinegar dissipates its sharp punch.', 'White pepper provides the signature authentic Chinese fiery throat heat.'],
    '{"calories":190,"protein":"20g","carbs":"12g","fat":"6g"}'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    image_url = EXCLUDED.image_url,
    cuisine = EXCLUDED.cuisine,
    category = EXCLUDED.category,
    food_type = EXCLUDED.food_type,
    ingredients = EXCLUDED.ingredients,
    instructions = EXCLUDED.instructions,
    preparation_time = EXCLUDED.preparation_time,
    cooking_time = EXCLUDED.cooking_time,
    total_time = EXCLUDED.total_time,
    difficulty = EXCLUDED.difficulty,
    servings = EXCLUDED.servings,
    rating = EXCLUDED.rating,
    tips = EXCLUDED.tips,
    nutrition = EXCLUDED.nutrition;